# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1accb8e819e3b5380e81ceb5dd304127b77f3eb6e9bd068e5710d40f68dbb485d8be05eadbb072195cf5f14dd5dc9f75767b48334c099fc84dac74c9f7553be

test:
  secret_key_base: 7ed40c8a012083b2c8eae30e3b58895c42de348e9a2839a8eb7573eee0d70b799fa91384dcb5cab1bab94414ea3e1ef0fde66a0c2cf21aaf820294cc4f022d47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
